metalk8s_elasticsearch_enabled: True


debug: false

remove_metal_k8s_temporary_file: true

es_addon_dir: '{{ kube_config_dir }}/addons/elasticsearch'
es_namespace: 'kube-ops'

fluentd_release_name: 'fluentd'
fluentd_chart: 'fluentd'
fluentd_version: '0.1.4'
fluentd_repo: 'https://kubernetes-charts-incubator.storage.googleapis.com'
fluentd_namespace: 'kube-ops'

fluent_bit_release_name: 'fluent-bit'
fluent_bit_chart: 'fluent-bit'
fluent_bit_version: '0.6.0'
fluent_bit_repo: 'https://kubernetes-charts.storage.googleapis.com'
fluent_bit_namespace: 'kube-ops'

kibana_chart: 'kibana'
kibana_version: '0.6.0'
kibana_repo: 'https://kubernetes-charts.storage.googleapis.com'
kibana_namespace: 'kube-ops'
kibana_release_name: 'kibana'

elasticsearch_exporter_chart: 'elasticsearch-exporter'
elasticsearch_exporter_version: '0.1.4'
elasticsearch_exporter_repo: 'https://kubernetes-charts.storage.googleapis.com'
# Note: When changing this name, the 'ServiceMonitor' manifest needs to be
# updated as well
elasticsearch_exporter_namespace: 'kube-ops'
# Note: When changing this name, the `ServiceMonitor` manifest needs to be
# updated as well
elasticsearch_exporter_release_name: 'es-exporter'

cerebro_repo: 'https://kubernetes-charts.storage.googleapis.com'
cerebro_version: '0.1.1'
cerebro_namespace: 'kube-ops'
cerebro_release_name: 'cerebro'
cerebro_chart: 'cerebro'
