{%- from "metalk8s/repo/macro.sls" import build_image_name with context -%}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: metalk8s-ui
    heritage: metalk8s
    app.kubernetes.io/name: metalk8s-ui
    app.kubernetes.io/component: ui
    app.kubernetes.io/part-of: metalk8s
    app.kubernetes.io/managed-by: salt
spec:
  selector:
    matchLabels:
      app: metalk8s-ui
  template:
    metadata:
      labels:
        app: metalk8s-ui
    spec:
      tolerations:
      - key: "node-role.kubernetes.io/bootstrap"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/infra"
        operator: "Exists"
        effect: "NoSchedule"
      nodeSelector:
        beta.kubernetes.io/os: linux
        node-role.kubernetes.io/infra: ''
      containers:
        - name: metalk8s-ui
          image: {{ build_image_name('metalk8s-ui') }}
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: 170Mi
            requests:
              cpu: 100m
              memory: 70Mi
          ports:
          - containerPort: 80
            name: http
            protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTP
          readinessProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTP
          volumeMounts:
          - name: metalk8s-ui-volume
            mountPath: /etc/metalk8s/ui/config
            readOnly: true
          - name: ui-branding-volume
            mountPath: /etc/metalk8s/ui/brand
            readOnly: true
      volumes:
        - name: metalk8s-ui-volume
          configMap:
            name: metalk8s-ui
        - name: ui-branding-volume
          configMap:
            name: ui-branding
