apiVersion: v1
kind: Pod
metadata:
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ""
    metalk8s.scality.com/config-digest: "{{ config_digest }}"
  creationTimestamp: null
  name: {{ name }}
  namespace: "kube-system"
  labels:
    component: {{ name }}
    tier: "control-plane"
spec:
  containers:
    - name: {{ name }}
      image: {{ image_name }}
      imagePullPolicy: IfNotPresent
      command:
      {%- for part in command %}
        - {{ part }}
      {%- endfor %}
      livenessProbe:
        failureThreshold: 8
        httpGet:
          host: {{ host }}
          path: /healthz
          port: {{ port }}
          scheme: {{ scheme }}
        initialDelaySeconds: 15
        timeoutSeconds: 15
{%- if ports is defined and ports %}
      ports:
      {{ ports | yaml(False) | indent(6, False) }}
{%- endif %}
      resources:
        requests:
          cpu: {{ requested_cpu }}
      volumeMounts:
        {%- for volume in volumes %}
        - mountPath: {{ volume.path }}
          name: {{ volume.name }}
          readOnly: true
        {%- endfor %}
{%- if sidecars is defined and sidecars %}
    {{ sidecars | yaml(False) | indent(4, False) }}
{%- endif %}
  priorityClassName: "system-cluster-critical"
  hostNetwork: true
  volumes:
    {%- for volume in volumes %}
    - hostPath:
        path: {{ volume.path }}
        type: {{ volume.get("type", "Directory") }}
      name: {{ volume.name }}
    {%- endfor %}
{%- if extra_volumes is defined and extra_volumes %}
    {{ extra_volumes | yaml(False) | indent(4, False) }}
{%- endif %}
status: {}
