docker_dns_servers_strict: False
helm_version: v2.9.1
helm_enabled: True
kube_basic_auth: True
kubeconfig_localhost: True
kubelet_authentication_token_webhook: True

# Request usage of the `overlay2` storage driver, even on pre-18.03 Docker
# installs.
# Whilst this is not guaranteed to work on 'old' kernels, we check whether we're
# running CentOS 7.4 or higher, with a kernel which contains all required
# backports.
docker_storage_options: -s overlay2 --storage-opt overlay2.override_kernel_check=true
