apiVersion: v1
appVersion: 2.23.0
description: OpenID Connect Identity (OIDC) and OAuth 2.0 Provider with Pluggable
  Connectors
home: https://github.com/dexidp/dex/
icon: https://github.com/dexidp/dex/raw/master/Documentation/logos/dex-glyph-color.png
keywords:
- dex
- oidc
maintainers:
- email: Kevin.Fox@pnnl.gov
  name: kfox1111
- email: shane.starcher@gmail.com
  name: sstarcher
- email: pete.brown@powerhrg.com
  name: rendhalver
- email: vi7alya@gmail.com
  name: vi7
name: dex
version: 2.10.0
