apiVersion: v1
appVersion: 0.7.3
description: MetalLB is a load-balancer implementation for bare metal Kubernetes clusters
home: https://metallb.universe.tf
icon: https://metallb.universe.tf/images/logo.png
keywords:
- load-balancer
- balancer
- lb
- bgp
- arp
- vrrp
- vip
maintainers:
- email: dave@natulte.net
  name: danderson
name: metallb
version: 0.9.5
