- name: 'install prometheus-operator'
  command: >-
    {{ bin_dir }}/helm upgrade prometheus-operator
    --install {{ prometheus_operator_release_name }}
    --repo {{ prometheus_operator_repo }}
    --version {{ prometheus_operator_version }}
    --namespace {{ prometheus_operator_namespace }}
  run_once: True
  delegate_to: "{{ groups['kube-master'][0] }}"

- name: 'create tempfile for kube-prometheus values'
  tempfile:
    state: file
    suffix: yml
  register: kube_prometheus_value_file
  run_once: True
  delegate_to: "{{ groups['kube-master'][0] }}"

- debug:
    var: kube_prometheus_value_file
  when: debug|bool
  run_once: True
  delegate_to: "{{ groups['kube-master'][0] }}"

- name: 'copy kube-prometheus values into temporary file'
  template:
    src: prometheus_values.yml
    dest: '{{ kube_prometheus_value_file.path }}'
  run_once: True
  delegate_to: "{{ groups['kube-master'][0] }}"

- name: 'create tempfile for kube-prometheus values'
  tempfile:
    state: file
    suffix: yml
  register: kube_prometheus_dashboard_file
  run_once: True
  delegate_to: "{{ groups['kube-master'][0] }}"

- debug:
    var: kube_prometheus_dashboard_file
  when: debug|bool
  run_once: True
  delegate_to: "{{ groups['kube-master'][0] }}"

- name: 'copy kube-prometheus dashboard into temporary file'
  copy:
    src: additionnal_dashboard.yml
    dest: '{{ kube_prometheus_dashboard_file.path }}'
  run_once: True
  delegate_to: "{{ groups['kube-master'][0] }}"

- name: 'remove old exporter-node objects (#113)'
  kube:
    kubectl: '{{ bin_dir }}/kubectl'
    namespace: '{{ kube_prometheus_namespace }}'
    label: chart=exporter-node-0.4.0,release=exporter-node
    resource: configmap,service,servicemonitor,endpoints
    state: 'absent'
  run_once: true
  delegate_to: "{{ groups['kube-master'][0] }}"

- name: 'get prometheus crd'
  command: >-
    {{ bin_dir }}/kubectl get
    customresourcedefinitions
    alertmanagers.monitoring.coreos.com
    prometheuses.monitoring.coreos.com
    servicemonitors.monitoring.coreos.com
  register: prometheus_crd
  run_once: True
  until: prometheus_crd is success
  check_mode: False
  changed_when: False
  retries: 10

- name: 'install kube-prometheus'
  command: >-
    {{ bin_dir }}/helm upgrade kube-prometheus
    --install {{ kube_prometheus_release_name }}
    --repo {{ kube_prometheus_repo }}
    --version {{ kube_prometheus_version }}
    --namespace {{ kube_prometheus_namespace }}
    -f {{ kube_prometheus_value_file.path }}
    -f {{ kube_prometheus_dashboard_file.path }}
  run_once: True
  delegate_to: "{{ groups['kube-master'][0] }}"

- name: 'remove unneeded kube-prometheus values file'
  file:
    dest: '{{ item }}'
    state: absent
  with_items: >-
    {{ [kube_prometheus_value_file.path,
        kube_prometheus_dashboard_file.path]|select|list }}
  when: remove_metal_k8s_temporary_file|bool
  run_once: True
  delegate_to: "{{ groups['kube-master'][0] }}"
