---
debug: false

metrics_server_repo: 'https://kubernetes-charts.storage.googleapis.com'
metrics_server_version: '2.0.2'
metrics_server_namespace: kube-system
metrics_server_release_name: metrics-server
metrics_server_chart: metrics-server

metrics_server_external_values: []

kube_metrics_server_uninstall: false
